app/base/models.py
# -*- encoding: utf-8 -*-
"""
License: MIT
Copyright (c) 2019 - present AppSeed.us
"""

from flask_login import UserMixin
from sqlalchemy import Binary, Column, Integer, String

from app import db, login_manager

from app.base.util import hash_pass

class User(db.Model, UserMixin):

    __tablename__ = 'User'

    id = Column(Integer, primary_key=True)
    username = Column(String, unique=True)
    email = Column(String, unique=True)
    password = Column(Binary)

    def __init__(self, **kwargs):
        for property, value in kwargs.items():
            # depending on whether value is an iterable or not, we must
            # unpack it's value (when **kwargs is request.form, some values
            # will be a 1-element list)
            if hasattr(value, '__iter__') and not isinstance(value, str):
                # the ,= unpack of a singleton fails PEP8 (travis flake8 test)
                value = value[0]

            if property == 'password':
                value = hash_pass( value ) # we need bytes here (not plain str)
                
            setattr(self, property, value)

    def __repr__(self):
        return str(self.username)


@login_manager.user_loader
def user_loader(id):
    return User.query.filter_by(id=id).first()

@login_manager.request_loader
def request_loader(request):
    username = request.form.get('username')
    user = User.query.filter_by(username=username).first()
    return user if user else None

app/base/forms.py
# -*- encoding: utf-8 -*-
"""
License: MIT
Copyright (c) 2019 - present AppSeed.us
"""

from flask_wtf import FlaskForm
from wtforms import TextField, PasswordField
from wtforms.validators import InputRequired, Email, DataRequired

## login and registration

class LoginForm(FlaskForm):
    username = TextField    ('Username', id='username_login'   , validators=[DataRequired()])
    password = PasswordField('Password', id='pwd_login'        , validators=[DataRequired()])

class CreateAccountForm(FlaskForm):
    username = TextField('Username'     , id='username_create' , validators=[DataRequired()])
    email    = TextField('Email'        , id='email_create'    , validators=[DataRequired(), Email()])
    password = PasswordField('Password' , id='pwd_create'      , validators=[DataRequired()])

app/base/__init__.py
# -*- encoding: utf-8 -*-
"""
License: MIT
Copyright (c) 2019 - present AppSeed.us
"""

from flask import Blueprint

blueprint = Blueprint(
    'base_blueprint',
    __name__,
    url_prefix='',
    template_folder='templates',
    static_folder='static'
)

app/base/routes.py
# -*- encoding: utf-8 -*-
"""
License: MIT
Copyright (c) 2019 - present AppSeed.us
"""

from flask import jsonify, render_template, redirect, request, url_for
from flask_login import (
    current_user,
    login_required,
    login_user,
    logout_user
)

from app import db, login_manager
from app.base import blueprint
from app.base.forms import LoginForm, CreateAccountForm
from app.base.models import User

from app.base.util import verify_pass

@blueprint.route('/')
def route_default():
    return redirect(url_for('base_blueprint.login'))

@blueprint.route('/error-<error>')
def route_errors(error):
    return render_template('errors/{}.html'.format(error))

## Login & Registration

@blueprint.route('/login', methods=['GET', 'POST'])
def login():
    login_form = LoginForm(request.form)
    if 'login' in request.form:
        
        # read form data
        username = request.form['username']
        password = request.form['password']

        # Locate user
        user = User.query.filter_by(username=username).first()
        
        # Check the password
        if user and verify_pass( password, user.password):

            login_user(user)
            return redirect(url_for('base_blueprint.route_default'))

        # Something (user or pass) is not ok
        return render_template( 'login/login.html', msg='Wrong user or password', form=login_form)

    if not current_user.is_authenticated:
        return render_template( 'login/login.html',
                                form=login_form)
    return redirect(url_for('home_blueprint.index'))

@blueprint.route('/create_user', methods=['GET', 'POST'])
def create_user():
    login_form = LoginForm(request.form)
    create_account_form = CreateAccountForm(request.form)
    if 'register' in request.form:

        username  = request.form['username']
        email     = request.form['email'   ]

        user = User.query.filter_by(username=username).first()
        if user:
            return render_template( 'login/register.html', msg='Username already registered', form=create_account_form)

        user = User.query.filter_by(email=email).first()
        if user:
            return render_template( 'login/register.html', msg='Email already registered', form=create_account_form)

        # else we can create the user
        user = User(**request.form)
        db.session.add(user)
        db.session.commit()

        return render_template( 'login/register.html', msg='User created please <a href="/login">login</a>', form=create_account_form)

    else:
        return render_template( 'login/register.html', form=create_account_form)

@blueprint.route('/logout')
def logout():
    logout_user()
    return redirect(url_for('base_blueprint.login'))

@blueprint.route('/shutdown')
def shutdown():
    func = request.environ.get('werkzeug.server.shutdown')
    if func is None:
        raise RuntimeError('Not running with the Werkzeug Server')
    func()
    return 'Server shutting down...'

## Errors

@login_manager.unauthorized_handler
def unauthorized_handler():
    return render_template('errors/403.html'), 403

@blueprint.errorhandler(403)
def access_forbidden(error):
    return render_template('errors/403.html'), 403

@blueprint.errorhandler(404)
def not_found_error(error):
    return render_template('errors/404.html'), 404

@blueprint.errorhandler(500)
def internal_error(error):
    return render_template('errors/500.html'), 500

app/base/templates/base-site-fullscreen.html
<!-- light-blue - v4.0.1 - 2018-10-31 -->

<!DOCTYPE html>
<html>
<head>
  
    <title>
        Flask Dashboard Light Blue - {% block title %}{% endblock %} | AppSeed
    </title>

    <link href="/static/assets/css/application.css" rel="stylesheet">
    <link rel="shortcut icon" href="/static/assets/img/favicon.png">

    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">
    <meta charset="utf-8">
    <script>
        /* yeah we need this empty stylesheet here. It's cool chrome & chromium fix
           chrome fix https://code.google.com/p/chromium/issues/detail?id=167083
                      https://code.google.com/p/chromium/issues/detail?id=332189
        */
    </script>

    <!-- Specific Page CSS goes HERE  -->
    {% block stylesheets %}{% endblock stylesheets %}

</head>
<body>

    <div class="single-widget-container">

      {% block content %}{% endblock content %}

    </div>

    {% include 'site_template/scripts.html' %}

    <!-- Specific Page JS goes HERE  -->
    {% block javascripts %}{% endblock javascripts %}

</body>
</html>

app/base/templates/base-site.html
<!-- light-blue - v4.0.1 - 2018-10-31 -->

<!DOCTYPE html>
<html>
<head>
  
    <title>
        Flask Dashboard Light Blue - {% block title %}{% endblock %} | AppSeed
    </title>

    <link href="/static/assets/css/application.css" rel="stylesheet">
    <link rel="shortcut icon" href="/static/assets/img/favicon.png">

    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">
    <meta charset="utf-8">
    <script>
        /* yeah we need this empty stylesheet here. It's cool chrome & chromium fix
           chrome fix https://code.google.com/p/chromium/issues/detail?id=167083
                      https://code.google.com/p/chromium/issues/detail?id=332189
        */
    </script>

    <!-- Specific Page CSS goes HERE  -->
    {% block stylesheets %}{% endblock stylesheets %}

</head>
<body>

    <div class="logo">
        <h4><a href="/">Val <strong>Gas</strong></a></h4>
    </div>

    {% include 'site_template/sidebar.html' %}

    <div class="wrap">

        {% include 'site_template/navigation.html' %}
        
        <div class="content container">

            {% block content %}{% endblock content %}

            {% include 'site_template/footer.html' %}

        </div>

        <div class="loader-wrap hiding hide">
            <i class="fa fa-circle-o-notch fa-spin"></i>
        </div>

    </div>

    {% include 'site_template/scripts.html' %}

    <!-- Specific Page JS goes HERE  -->
    {% block javascripts %}{% endblock javascripts %}

</body>
</html>

app/base/templates/login/login.html
{% extends "base-site-fullscreen.html" %}

{% block title %} Login {% endblock %} 

{% block content %}
        
    <section class="widget login-widget">
        <header class="text-align-center">
            <h4>
                {% if msg %}
                    {{ msg | safe }}
                {% else %}
                    Sign In
                {% endif %}               
            </h4>
        </header>
        <div class="body">

            <form role="form" method="post" action="">

                {{ form.hidden_tag() }} 
                
                <fieldset>

                    <div class="form-group">
                        <label for="username">Username</label>
                        <div class="input-group">
                            <span class="input-group-addon">
                                <i class="fa fa-user"></i>
                            </span>
                            {{ form.username(placeholder="Username", class="form-control input-lg input-transparent") }}
                        </div>
                    </div>
                    
                    <div class="form-group">
                        <label for="password" >Password</label>

                        <div class="input-group input-group-lg">
                            <span class="input-group-addon">
                                <i class="fa fa-lock"></i>
                            </span>
                            {{ form.password(placeholder="Password", class="form-control input-lg input-transparent", type="password") }}
                        </div>
                    </div>
                </fieldset>
                <div class="form-actions">
                    <button type="submit" name="login" class="btn btn-block btn-lg btn-danger">
                        <span class="small-circle"><i class="fa fa-caret-right"></i></span>
                        <small>Login</small>
                    </button>
                    <a class="forgot" href={{ url_for('base_blueprint.create_user') }} >Don't have an account? Register</a>
                </div>
            </form>
        </div>
        <footer>
            <div class="facebook-login">
                <a href="#s"><span><i class="fa fa-facebook-square fa-lg"></i> LogIn with Facebook</span></a>
            </div>
        </footer>
    </section>

{% endblock content %}

app/base/templates/login/register.html
{% extends "base-site-fullscreen.html" %}

{% block title %} Register {% endblock %} 

{% block content %}

    <section class="widget login-widget">
        <header class="text-align-center">
            <h4>
                {% if msg %}
                    {{ msg | safe }}
                {% else %}
                    Sign In
                {% endif %}    
            </h4>
        </header>
        <div class="body">

            <form role="form" method="post" action="">

                {{ form.hidden_tag() }} 

                <fieldset>

                    <div class="form-group">
                        <label for="username" >Username</label>
                        <div class="input-group">
                            <span class="input-group-addon">
                                <i class="fa fa-user"></i>
                            </span>
                            {{ form.username(placeholder="Username", class="form-control input-lg input-transparent") }}
                        </div>
                    </div>
                    
                    <div class="form-group">
                        <label for="email" >Email</label>
                        <div class="input-group">
                            <span class="input-group-addon">
                                <i class="fa fa-envelope"></i>
                            </span>
                            {{ form.email(placeholder="Email", class="form-control input-lg input-transparent") }}
                        </div>
                    </div>

                    <div class="form-group">
                        <label for="password" >Password</label>

                        <div class="input-group input-group-lg">
                            <span class="input-group-addon">
                                <i class="fa fa-lock"></i>
                            </span>
                            {{ form.password(placeholder="Password", class="form-control input-lg input-transparent", type="password") }}
                        </div>
                    </div>
                </fieldset>
                <div class="form-actions">
                    <button type="submit" name="register" class="btn btn-block btn-lg btn-danger">
                        <span class="small-circle"><i class="fa fa-caret-right"></i></span>
                        <small>Register</small>
                    </button>
                    <a class="forgot" href={{ url_for('base_blueprint.login') }} >Have an account? Login</a>
                </div>
            </form>
        </div>
        <footer>
            <div class="facebook-login">
                <a href="#"><span><i class="fa fa-facebook-square fa-lg"></i> LogIn with Facebook</span></a>
            </div>
        </footer>
    </section>

{% endblock content %}

app/base/templates/site_template/footer.html
    <footer class="content-footer">
        &copy; Flatlogic - <a href="https://appseed.us/admin-dashboards/flask-dashboard-light-blue">Flask dashboard Light Blue</a> provided by AppSeed 
    </footer>

app/base/templates/site_template/navigation.html
<header class="page-header">
    <div class="navbar">
        <ul class="nav navbar-nav navbar-right pull-right">
            <li class="visible-phone-landscape">
                <a href="#" id="search-toggle">
                    <i class="fa fa-search"></i>
                </a>
            </li>
            <li class="dropdown">
                <a href="#" title="Messages" id="messages"
                class="dropdown-toggle"
                data-toggle="dropdown">
                    <i class="glyphicon glyphicon-comment"></i>
                </a>
                <ul id="messages-menu" class="dropdown-menu messages" role="menu">
                    <li role="presentation">
                        <a href="#" class="message">
                            <img src="/static/assets/img/1.png" alt="">
                            <div class="details">
                                <div class="sender">Jane Hew</div>
                                <div class="text">
                                    Hey, John! How is it going? ...
                                </div>
                            </div>
                        </a>
                    </li>
                    <li role="presentation">
                        <a href="#" class="message">
                            <img src="/static/assets/img/2.png" alt="">
                            <div class="details">
                                <div class="sender">Alies Rumiancaŭ</div>
                                <div class="text">
                                    I'll definitely buy this template
                                </div>
                            </div>
                        </a>
                    </li>
                    <li role="presentation">
                        <a href="#" class="message">
                            <img src="/static/assets/img/3.png" alt="">
                            <div class="details">
                                <div class="sender">Michał Rumiancaŭ</div>
                                <div class="text">
                                    Is it really Lore ipsum? Lore ...
                                </div>
                            </div>
                        </a>
                    </li>
                    <li role="presentation">
                        <a href="#" class="text-align-center see-all">
                            See all messages <i class="fa fa-arrow-right"></i>
                        </a>
                    </li>
                </ul>
            </li>
            <li class="dropdown">
                <a href="#" title="8 support tickets"
                class="dropdown-toggle"
                data-toggle="dropdown">
                    <i class="glyphicon glyphicon-globe"></i>
                    <span class="count">8</span>
                </a>
                <ul id="support-menu" class="dropdown-menu support" role="menu">
                    <li role="presentation">
                        <a href="#" class="support-ticket">
                            <div class="picture">
                                <span class="label label-important"><i class="fa fa-bell-o"></i></span>
                            </div>
                            <div class="details">
                                Check out this awesome ticket
                            </div>
                        </a>
                    </li>
                    <li role="presentation">
                        <a href="#" class="support-ticket">
                            <div class="picture">
                                <span class="label label-warning"><i class="fa fa-question-circle"></i></span>
                            </div>
                            <div class="details">
                                "What is the best way to get ...
                            </div>
                        </a>
                    </li>
                    <li role="presentation">
                        <a href="#" class="support-ticket">
                            <div class="picture">
                                <span class="label label-success"><i class="fa fa-tag"></i></span>
                            </div>
                            <div class="details">
                                This is just a simple notification
                            </div>
                        </a>
                    </li>
                    <li role="presentation">
                        <a href="#" class="support-ticket">
                            <div class="picture">
                                <span class="label label-info"><i class="fa fa-info-circle"></i></span>
                            </div>
                            <div class="details">
                                12 new orders has arrived today
                            </div>
                        </a>
                    </li>
                    <li role="presentation">
                        <a href="#" class="support-ticket">
                            <div class="picture">
                                <span class="label label-important"><i class="fa fa-plus"></i></span>
                            </div>
                            <div class="details">
                                One more thing that just happened
                            </div>
                        </a>
                    </li>
                    <li role="presentation">
                        <a href="#" class="text-align-center see-all">
                            See all tickets <i class="fa fa-arrow-right"></i>
                        </a>
                    </li>
                </ul>
            </li>
            <li class="divider"></li>
            <li class="hidden-xs">
                <a href="#" id="settings"
                title="Settings"
                data-toggle="popover"
                data-placement="bottom">
                    <i class="glyphicon glyphicon-cog"></i>
                </a>
            </li>
            <li class="hidden-xs dropdown">
                <a href="#" title="Account" id="account"
                class="dropdown-toggle"
                data-toggle="dropdown">
                    <i class="glyphicon glyphicon-user"></i>
                </a>
                <ul id="account-menu" class="dropdown-menu account" role="menu">
                    <li role="presentation" class="account-picture">
                        <img src="/static/assets/img/2.png" alt="">
                        
                        {{ current_user.username }}
                    </li>
                    <li role="presentation">
                        <a href="#" class="link">
                            <i class="fa fa-user"></i>
                            Profile
                        </a>
                    </li>
                    <li role="presentation">
                        <a href="#" class="link">
                            <i class="fa fa-calendar"></i>
                            Calendar
                        </a>
                    </li>
                    <li role="presentation">
                        <a href="#" class="link">
                            <i class="fa fa-inbox"></i>
                            Inbox
                        </a>
                    </li>
                </ul>
            </li>
            <li class="visible-xs">
                <a href="#"
                class="btn-navbar"
                data-toggle="collapse"
                data-target=".sidebar"
                title="">
                    <i class="fa fa-bars"></i>
                </a>
            </li>
            <li class="hidden-xs">
              <a href={{ url_for('base_blueprint.logout') }} ><i class="glyphicon glyphicon-off"></i></a></li>
        </ul>
        <form id="search-form" class="navbar-form pull-right" role="search">
            <input type="search" class="form-control search-query" placeholder="Search...">
        </form>
        <div class="notifications pull-right">
            <div class="alert pull-right">
                <a href="#" class="close ml-xs" data-dismiss="alert">&times;</a>
                <i class="fa fa-info-circle mr-xs"></i> Check out Light Blue <a id="notification-link" href="#">settings</a> on the right!
            </div>
        </div>
    </div>
</header>  

app/base/templates/site_template/scripts.html
    <!-- common libraries. required for every page-->
    <script src="/static/assets/lib/jquery/dist/jquery.min.js"></script>
    <script src="/static/assets/lib/jquery-pjax/jquery.pjax.js"></script>
    <script src="/static/assets/lib/bootstrap-sass/assets/javascripts/bootstrap.min.js"></script>
    <script src="/static/assets/lib/widgster/widgster.js"></script>
    <script src="/static/assets/lib/underscore/underscore.js"></script>

    <!-- common application js -->
    <script src="/static/assets/js/app.js"></script>
    <script src="/static/assets/js/settings.js"></script>

    <!-- common templates -->
    <script type="text/template" id="settings-template">
        <div class="setting clearfix">
            <div>Sidebar on the</div>
            <div id="sidebar-toggle" class="pull-left btn-group" data-toggle="buttons-radio">
                <% onRight = sidebar == 'right'%>
                <button type="button" data-value="left" class="btn btn-sm btn-default <%= onRight? '' : 'active' %>">Left</button>
                <button type="button" data-value="right" class="btn btn-sm btn-default <%= onRight? 'active' : '' %>">Right</button>
            </div>
        </div>
        <div class="setting clearfix">
            <div>Sidebar</div>
            <div id="display-sidebar-toggle" class="pull-left btn-group" data-toggle="buttons-radio">
                <% display = displaySidebar%>
                <button type="button" data-value="true" class="btn btn-sm btn-default <%= display? 'active' : '' %>">Show</button>
                <button type="button" data-value="false" class="btn btn-sm btn-default <%= display? '' : 'active' %>">Hide</button>
            </div>
        </div>
    </script>

app/base/templates/site_template/sidebar.html
<nav id="sidebar" class="sidebar nav-collapse collapse">

    <ul id="side-nav" class="side-nav">
        <li class="active">
            <a href="/"><i class="fa fa-home"></i> <span class="name">Dashboard</span></a>
        </li>
        <li class="">
            <a href="/typography"><i class="fa fa-font"></i> Typography</a></li>
        </li>
        <li class="">
            <a href="/tables"><i class="fa fa-table"></i> Tables</a></li>
        </li>
        <li class="">
            <a href="/notifications"><i class="fa fa-bell"></i> Notifications</a></li>
        </li>

        <li class="">
            <a href="/production-process"><i class="fa fa-magic"></i>Production process</a>
        </li>


        <li class="panel ">
            <a class="accordion-toggle collapsed" data-toggle="collapse"
                data-parent="#side-nav" href="#elements-collapse"><i class="fa fa-magic"></i> <span class="name">Users & Permissions</span></a>
            <ul id="elements-collapse" class="panel-collapse collapse ">
                <li class=""><a href="/charts">Users</a></li>
                <li class=""><a href="/icons">Permissions</a></li>
            </ul>
        </li>
    </ul>
</nav>    